export const CART_ADD_ITEM = 'CART_ADD_ITEM'

export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM'

export const CART_SAVING_SHIPPING = 'CART_SAVING_SHIPPING'

export const CART_PAYMENT_METHOD = 'CART_PAYMENT_METHOD'

export const CART_CLEAR_ITEMS = 'CART_CLEAR_ITEMS'